### ISSUE TITLE
Anime image slider

### ISSUE THREAD

**Issue by Anirban-1490** [Dezenix/frontend-reactjs#43]
### Description

Anime image slider is a image slider with both images and text for info about anime with full responsiveness

### Screenshots

![Opera Snapshot_2022-04-02_004457_uplist netlify app](https://user-images.githubusercontent.com/82874704/161327517-fa05b12a-5820-4a51-be47-9387deff2565.png)

### in mobile view

![Opera Snapshot_2022-04-02_004525_uplist netlify app](https://user-images.githubusercontent.com/82874704/161327568-2db24261-0d43-43b5-ac1c-d1a151ba161d.png)

### Additional information

Please assign me this under GSSOC22

**Comment by Anirban-1490** [comment]
Please assign me this under GSSOC22

**Comment by Abirpal202049** [comment]
All the Best 😊
Try to finish the work within a week

**Comment by Anirban-1490** [comment]
> All the Best 😊 Try to finish the work within a week

k
