### ISSUE TITLE
Animated Product Cards

### ISSUE THREAD

**Issue by mishrashree18** [Dezenix/frontend-reactjs#8]
### Description

Follow contribution guidelines and code of conduct
Create a responsive, animated product card component using Reactjs which can be used in websites

### Additional information

Make the UI impressive

**Comment by IAmTamal** [comment]
Hey, can i work on this issue ?

**Comment by mishrashree18** [comment]
> Hey, can i work on this issue ?

Assigned! Start working

**Comment by Ovenoboyo** [comment]
Hi @IAmTamal 
Please read this https://github.com/Dezenix/frontend-reactjs/pull/14#issuecomment-986525570
